<a href="https://colab.research.google.com/github/1908Deepak/Complete_NLP_Series/blob/master/Day_6_Word_Embedding_Techniques_using_Embedding_Layer_in_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Word Embedding Techniques using Embedding Layer in keras**

In [30]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [33]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [70]:
#vocalbulary size
vocab_size = 500

**One Hot Representation**

In [71]:
onehot =[one_hot(words,vocab_size)for words in sent]
print(onehot)

[[23, 474, 158, 367], [23, 474, 158, 226], [23, 355, 158, 155], [144, 184, 302, 81, 452], [144, 184, 302, 81, 4], [324, 23, 265, 158, 427], [442, 346, 225, 81]]


**Word Embedding Representation**

In [72]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [37]:
import numpy as np

In [92]:
#pre padding
sent_length =8
embedded_docs = pad_sequences(onehot,padding='pre',maxlen =sent_length)
print(embedded_docs)

[[  0   0   0   0  23 474 158 367]
 [  0   0   0   0  23 474 158 226]
 [  0   0   0   0  23 355 158 155]
 [  0   0   0 144 184 302  81 452]
 [  0   0   0 144 184 302  81   4]
 [  0   0   0 324  23 265 158 427]
 [  0   0   0   0 442 346 225  81]]


In [93]:
# feature size
dim =8

In [94]:
model=Sequential()
model.add(Embedding(vocab_size,8))
model.compile('adam','mse')

In [95]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [96]:
# 'the glass of milk'
embedded_docs[0]

array([  0,   0,   0,   0,  23, 474, 158, 367], dtype=int32)

In [97]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
[[[-0.02829522 -0.01896539 -0.03463118  0.03174325 -0.04326433
    0.03636492  0.02978989  0.02980789]
  [-0.02829522 -0.01896539 -0.03463118  0.03174325 -0.04326433
    0.03636492  0.02978989  0.02980789]
  [-0.02829522 -0.01896539 -0.03463118  0.03174325 -0.04326433
    0.03636492  0.02978989  0.02980789]
  [-0.02829522 -0.01896539 -0.03463118  0.03174325 -0.04326433
    0.03636492  0.02978989  0.02980789]
  [ 0.00102108  0.02451294 -0.01431308 -0.01147349 -0.00227207
   -0.04245691 -0.03855885  0.03908935]
  [ 0.02835551  0.03133564 -0.03654945  0.01657145  0.04172132
   -0.02300218  0.0260191   0.02727046]
  [ 0.00304423  0.023376   -0.03204205 -0.02140065  0.02944313
   -0.02695532 -0.04025048  0.04790166]
  [-0.01238452  0.03538394  0.00139848 -0.0434539  -0.01690253
    0.03606517  0.04105805 -0.03852029]]

 [[-0.02829522 -0.01896539 -0.03463118  0.03174325 -0.04326433
    0.03636492  0.02978989  0.02980789]
  [-0.02829522 -0.01896539 -0.03

In [91]:
embedded_docs.shape

(7, 10)